### ISSUE TITLE
[Compatability Issue] Ernie's Modern UI - Compact Mode

### ISSUE THREAD

**Issue by SirMotte** [ClipplerBlood/journal-improvements#2]
Just wanted to report an compatibility issue with the [Ernie's Modern UI Module.](https://github.com/ernieayala/ernies-modern-layout)
When using the compact mode provided by said module, the edit buttons are no longer shown.

In case you're in the mood to take a look at why this occurs (hopefully some simple css conflict), I would highly appreciate a compatability patch :).

Feel free to dismiss this request, if you don't want to open Pandora's box by providing support for other modules that mess with the UI.

![grafik](https://user-images.githubusercontent.com/82598692/200063147-f0728b1e-e0ef-4ba1-9f88-aac3318d84f6.png)
![grafik](https://user-images.githubusercontent.com/82598692/200063330-9f2fdd2c-9b76-4c11-ac71-a7cfb6b35ad7.png)

**Comment by ClipplerBlood** [comment]
Ty for the clear explanation
It should be fixed in version 0.5.4

You can pre-download it here (via foundry manifest url)
https://github.com/ClipplerBlood/journal-improvements/releases/download/0.5.4/module.json

If it works fine I'll publish the release 😄

**Comment by SirMotte** [comment]
> https://github.com/ClipplerBlood/journal-improvements/releases/download/0.5.4/module.json

Fixed! Thank you so much!
