### ISSUE TITLE
Journals don't close after edits

### ISSUE THREAD

**Issue by ssligh** [ClipplerBlood/journal-improvements#3]
After editing a journal, I'm not able to close the journal, nor collapse it by double clicking the title bar. I am using Firefox 106.0.5 with Foundry 10 on the Forge hosting service. When I click the Save button it throws the following error:

Uncaught TypeError: (intermediate value).apply is not a function
[No packages detected]
    jQuery 5
jquery.min.js:2:43064

The issue persists even with all other modules disabled.

**Comment by ClipplerBlood** [comment]
Does it also happen when using chromium browsers?

**Comment by ssligh** [comment]
Yes, same behavior in Chrome (106.0.5249.119) and it throws this error not when I click the edit button, but as soon as I start to make an edit:
jquery.min.js:2 Uncaught TypeError: ((S.event.special[o.origType] || {}).handle || o.handler).apply is not a function
[No packages detected]
    at HTMLDivElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
    at Object.trigger (jquery.min.js:2:71659)
    at Object.simulate (jquery.min.js:2:72162)
    at HTMLDocument.i (jquery.min.js:2:72451)
________________________________

**Comment by ClipplerBlood** [comment]
Unfortunately I cannot replicate
Maybe it's an error due to the Forge?

**Comment by danielcoutz** [comment]
I'm having the same issue and I don't use the Forge.

**Comment by danielcoutz** [comment]
If you click edit button type anithing and click in save and close button you will get the error below:

Uncaught TypeError: ((S.event.special[o.origType] || {}).handle || o.handler).apply is not a function
[No packages detected]
    at HTMLDivElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
    at Object.trigger (jquery.min.js:2:71659)
    at Object.simulate (jquery.min.js:2:72162)
    at HTMLDocument.i (jquery.min.js:2:72451)

**Comment by ssligh** [comment]
Don't know if this helps, but I noticed the problem stopped when I disabled autosave in the module settings.

**Comment by ClipplerBlood** [comment]
Does it also happen with the markdown editor?
I think I may have found the issue

**Comment by ClipplerBlood** [comment]
Let me know if this fixes it
https://github.com/ClipplerBlood/journal-improvements/releases/download/0.6.1/module.json
If so, I'll release the update

**Comment by ssligh** [comment]
Seems to be working now, thanks.
