### ISSUE TITLE
Question: How to resize images?

### ISSUE THREAD

**Issue by Sphinx2k** [ClipplerBlood/journal-improvements#4]
I love this module. It fits so nicely in my workflow. 
One thing i don't get is how to resize an image when using the "ProseMirror" editor engine?
Is it even possible in an easy way with drag and dropping the image border? 
If i switch to TinyMCE some markdowns like > for blockquote don't work. But i can resize images.

**Comment by ClipplerBlood** [comment]
Unfortunately that's an issue with Foundry's ProseMirror editor itself. Even when using the default journals that editor is not able to resize images. 
Maybe you could try reporting the issue to foundry directly?
The only fix is to use TinyMCE or to edit the image style directly in the page's html source

Cheers!
