### ISSUE TITLE
[Issue/Bug] Module not working with Pathfinder 2

### ISSUE THREAD

**Issue by SebastianH17** [ClipplerBlood/journal-improvements#8]
Nice module, I am using Foundry with two systems, Starfinder and Pathfinder 2. In Starfinder everything seems to work, but in PF2 most options do not seem to do anything. 

Not sure what else I could provide here, so I just wanted to say thank for your all of your hard work ^^

**Comment by ClipplerBlood** [comment]
Hi, have you tried switching the sheet from the PF2E journal sheet to the Improved Journal sheet?
![image](https://user-images.githubusercontent.com/82539651/208718262-567f01c8-cb3a-4b89-b484-108c838b8484.png)

**Comment by SebastianH17** [comment]
Thank you, I had not considered to do that, while I do not have time to check it in detail, thank you so much for your comment ^^
